### ISSUE TITLE
 Does not work with version 3.13.1

### ISSUE THREAD

**Issue by DabinSon** [NuLL3rr0r/babaei.net#2]

**Comment by NuLL3rr0r** [comment]
Thank you for reporting this. I didn't quite get which post you are referring to. I must assume it's this post [2016-01-08-post-processing-effects-in-cocos2d-x](https://github.com/NuLL3rr0r/babaei.net/tree/master/2016-01-08-post-processing-effects-in-cocos2d-x).

If that's the case, sure I'll find some time and try to fix that.

**Comment by madrazo** [comment]
Yes, the Cocos postprocessing effects compiles OK but the color is not shown (like no shader is applied).  😭

**Comment by lazerfalcon** [comment]
@madrazo and @NuLL3rr0r:
I'm using cocos2dx 3.10.  I've made some modifications to the code to use `Node` instead of `Layer` since there's no need to use `Layer`s anymore.  Let me know if you want to see the rest of the code, but I believe that only these changes **need** to be made to make everything work:
```
void PostProcess::draw(Node* node)
{
    if (node != nullptr)
    {
        m_Pimpl->renderTexture->beginWithClear(0.0f, 0.0f, 0.0f, 0.0f);
        node->visit(_director->getRenderer(), _modelViewTransform, true);
        m_Pimpl->renderTexture->end();
    }
    else
        m_Pimpl->renderTexture->clear(0.0f, 0.0f, 0.0f, 0.0f);
}
```
Note that this also allows for dynamic switching of the nodes that are being processed by the `draw()` method.

**Comment by madrazo** [comment]
Oh wow. That was it 😂 I'm on 3.15.1. Thank you very much

**Comment by madrazo** [comment]
Just to let you know.
I tried changing
`auto sprite = Sprite::create("HelloWorld.png");`
with
`auto sprite = BillBoard::create("HelloWorld.png");`
but it didn't work 😄

**Comment by NuLL3rr0r** [comment]
Thank you @lazerfalcon and @madrazo I updated the post with the following:

__Update [2020/10/23]:__ _Since I wrote this tutorial many things has changed in Cocos2d-x and I haven't been using it in years as I switched to Unreal Engine 4. According to [this GitHub issue](https://github.com/NuLL3rr0r/babaei.net/issues/2) opened by my blog readers, in order for this code to work there has to be some modifications to the code which is provided on that issue by @lazerfalcon and @madrazo. I was also [having trouble with render to texture on Sprite3D](https://stackoverflow.com/questions/34595594/cocos2dx-sprite3d-wont-render-to-texture/39073958#39073958) which seems to have been solved in newer versions._
